runx - abort if no xauthority
With the new laptop I'm seeing some things (e.g. wallpaper) triggered by, I think, udev
and such hang indefinitely.

This would probably self-resolve if I then started X (I'm guessing my
old laptop does the same but I don't notice because I always start X),
but since I'm playing with transitioning to Wayland, I'd prefer to have
these not hang.

diff --git a/home_nodot/bin/runx b/home_nodot/bin/runx
--- a/home_nodot/bin/runx
+++ b/home_nodot/bin/runx
@@ -20,4 +20,9 @@ if [ $UID -eq 0 ]; then
   set -- su will -c "$cmd"
 fi
 
+if [ ! $xauthority ]; then
+  echo "Can't identify xauthority - not running X?" >&2
+  exit 1
+fi
+
 DISPLAY=:0 XAUTHORITY="$(xauthority)" "$@"
