fix spotify-control style issues

diff --git a/home_nodot/bin/spotify-control b/home_nodot/bin/spotify-control
--- a/home_nodot/bin/spotify-control
+++ b/home_nodot/bin/spotify-control
@@ -1,19 +1,18 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 # Collect DBUS_SESSION_BUS_ADDRESS from running process
 set_dbus_adress () {
 	USER=$1
 	PROCESS=$2
-	PID=`pgrep -o -u $USER $PROCESS`
+  PID=$(pgrep -o -u "$USER" "$PROCESS")
 	ENVIRON=/proc/$PID/environ
 
-	if [ -e $ENVIRON ]
-	 then
-	export `grep -z DBUS_SESSION_BUS_ADDRESS $ENVIRON`
-	 else
-	echo "Unable to set DBUS_SESSION_BUS_ADDRESS."
-	exit 1
+	if [ -e "$ENVIRON" ]; then
+    export $(grep -z DBUS_SESSION_BUS_ADDRESS "$ENVIRON")
+  else
+    echo "Unable to set DBUS_SESSION_BUS_ADDRESS."
+    exit 1
 	fi
 }
 
@@ -21,7 +20,7 @@ spotify_cmd () {
 	dbus-send \
     --print-reply \
     --dest=org.mpris.MediaPlayer2.spotify \
-    /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.$1 1> /dev/null
+    /org/mpris/MediaPlayer2 "org.mpris.MediaPlayer2.Player.$1" 1> /dev/null
 }
 
 spotify_query () {
@@ -34,7 +33,7 @@ spotify_query () {
 }
 
 quit_message () {
-  printf "Usage: %s {play|pause|playpause|next|previous|stop|playstatus|<spotify URI>}\n" $(basename $0)
+  printf "Usage: %s {play|pause|playpause|next|previous|stop|playstatus|<spotify URI>}\n" "$(basename "$0")"
 	exit 67
 }
 
@@ -44,9 +43,9 @@ if [ "$#" -ne "1" ]; then
 fi
 
 # Check if DBUS_SESSION is set
-if [ -z $DBUS_SESSION_BUS_ADDRESS ]; then
+if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
 	#echo "DBUS_SESSION_BUS_ADDRESS not set. Guessing."
-	set_dbus_adress `whoami` spotify
+  set_dbus_adress "$(whoami)" spotify
 fi
 
 case "$1" in
